const SECTOR_AREAS = {
  "Accountancy": [
    "Assurance",
    "Business Management",
    "Digital and Data Management",
    "Financial and Transaction Management",
    "Internal Audit",
    "Risk, Compliance and Governance",
    "Sustainability Reporting and Assurance",
    "Taxation"
  ],
  "Aerospace": [
    "Aerospace and Engineering Fundamentals",
    "Aircraft Maintenance",
    "Business Development and Strategy Management",
    "Component Maintenance",
    "Engine Manufacturing and Maintenance",
    "Enterprise Risk Management",
    "General Management",
    "Health, Safety and Environment Management",
    "Maintenance Management",
    "Manufacturing and Operations",
    "Precision Engineering",
    "Productivity and Innovation",
    "Quality Management",
    "Special Processes",
    "Supply Chain Management",
    "Technical and Engineering Design",
    "Technology Management"
  ],
  "Agrifood": [
    "Business Management",
    "Environmental Sustainability",
    "Farming Operations",
    "Food Regulatory Compliance",
    "Infocomm Technology",
    "Maintenance Management",
    "Quality Management",
    "Stakeholder and Customer Management",
    "Sustainability Management",
    "Technology Application",
    "Technology Management",
    "Workplace Safety and Health"
  ],
  "Air Transport": [
    "Aircraft Operations",
    "Airline Operations",
    "Airport Engineering",
    "Airport Operations",
    "Airside Operations",
    "Business Management",
    "Cargo Operations",
    "Commercial Management",
    "Customer and Passenger Services",
    "Flight Operations",
    "Ground Handling Services and Operations",
    "In Flight Catering",
    "In Flight Services",
    "Organisational Development",
    "Productivity and Innovation",
    "Safety and Security Management",
    "Safety Management",
    "Technology Management"
  ],
  "Arts": [
    "Art Form Specific Instruction",
    "Arts Education for Community",
    "Arts Learning Delivery",
    "Arts Learning Design",
    "Assessment and Accreditation",
    "Automation",
    "Costume, Hair and Make-up",
    "General Management",
    "Ideation",
    "Lighting",
    "Media",
    "Production",
    "Research and Innovation",
    "Set and Props",
    "Sound"
  ],
  "BioPharmaceuticals Manufacturing": [
    "Engineering and Maintenance",
    "General Management",
    "Health, Safety and Environment",
    "Process Development/Manufacturing Science and Technology (MS&T)",
    "Production",
    "Quality Assurance",
    "Quality Control"
  ],
  "Built Environment": [
    "Analytical Thinking",
    "Building Management",
    "Business and Project Finance",
    "Business Management",
    "Construction Methods",
    "Design",
    "Discipline Engineering Specialisation",
    "Engineering Design Management",
    "Environment Management",
    "Equipment Management",
    "Feasibility Assessment",
    "Incident Management",
    "Information Technology Management",
    "Maintenance",
    "People Development and Management",
    "Process Improvement",
    "Procurement Management",
    "Production Management",
    "Project Management",
    "Quality Management",
    "Technical Drawing",
    "Technology Management",
    "Workplace Safety and Health (WSH) Management"
  ],
  "Carbon Services and Trading": [
    "Advisory",
    "Carbon Project Development",
    "Financial Intermediation",
    "Governance and Infrastructure",
    "Legal and Insurance"
  ],
  "Critical Core Skills": [
    "Interacting With Others",
    "Staying Relevant",
    "Thinking Critically"
  ],
  "Design": [
    "Analytical Thinking",
    "Business Development",
    "Business Strategy",
    "Corporate Governance and Policies",
    "Creativity",
    "Design Communication",
    "General Management",
    "Stakeholder and Customer Management",
    "Technical Craft"
  ],
  "Early Childhood": [
    "Child Learning and Development",
    "Child Safety and Well-Being",
    "Early Intervention and Learning Support Development",
    "Families and Community Partnership",
    "Family & Community Partnership",
    "Family and Community Partnership",
    "Operations and Management",
    "Professional Practice and Development",
    "Workforce Development and Engagement"
  ],
  "Electronics": [
    "Automation Management",
    "Big Data Analytics",
    "Business Continuity Management",
    "Maintenance",
    "Manufacturing and Operations",
    "Network Technology Management",
    "Networking Building",
    "Organisational Development",
    "People Management",
    "Product Development and Testing",
    "Production Management",
    "Productivity and Innovation",
    "Quality Management",
    "Risk Management",
    "Strategy Planning and Implementation",
    "System Integration",
    "Technology Road Mapping",
    "Workplace Safety and Health Management"
  ],
  "Energy and Chemicals": [
    "Business and Organisational Management",
    "Data Analytics",
    "Discipline Engineering Specialisation",
    "Discipline Engineering Support Management",
    "Emergency Response and Crisis Management",
    "Engineering Design and Project Management",
    "Health, Safety and Environment Management",
    "Laboratory Management",
    "Learning and Development Management",
    "Maintenance Management",
    "Process Engineering Management",
    "Process Operations Management",
    "Process Safety Management",
    "Quality Assurance and Quality Control Management",
    "Research and Development Management",
    "Supply Chain and Production Planning Management",
    "Technology Application Management"
  ],
  "Energy and Power": [
    "Business and Organisational Management",
    "Business Development",
    "Data Analytics",
    "Electricity Imports",
    "Emergency Response and Crisis Management",
    "Energy Demand Management",
    "Energy Management Operations",
    "Energy Trading Management",
    "General Management",
    "Health, Safety and Environment (HSE) Management",
    "Maintenance Management",
    "Operations and User Support",
    "Planning and Design",
    "Process Monitoring Management",
    "Project and Contract Management",
    "Sales and Marketing",
    "Site and Equipment Management",
    "Stakeholder and Customer Management"
  ],
  "Engineering Services": [
    "Business and Organisational Management",
    "Business Development",
    "Business Finance",
    "Discipline Engineering Specialisation",
    "Engineering Construction, Operations and Maintenance",
    "Engineering Design Management",
    "General Management",
    "Health, Safety and Environment (HSE) Management",
    "People Development",
    "Procurement Management",
    "Project Finance",
    "Project Management",
    "Technology Road Mapping",
    "Workplace Safety and Health (WSH) Management"
  ],
  "Environmental Services": [
    "Business Management",
    "Circular Economy",
    "Cleaning Operations",
    "Environmental Management System Management",
    "Equipment Maintenance",
    "People Development",
    "Pest Management Operations",
    "Productivity",
    "Stakeholder and Customer Management",
    "Technology Management",
    "Transportation Management",
    "Waste Management Operations",
    "Workplace Safety and Health Management"
  ],
  "Financial Services": [
    "Business Development and Strategy Management",
    "Customer Relationship and Stakeholder Management",
    "Data Analytics and Information Technology Management",
    "GenAI",
    "Internal Audit",
    "Investment and Financial Management",
    "People Management",
    "Product, Sales and Market Management",
    "Risk Management, Governance and Regulatory Compliance",
    "Sustainable Finance",
    "Taxation"
  ],
  "Food Manufacturing": [
    "Alternative or Novel Food",
    "Automation Management",
    "Big Data",
    "Business to Business Management",
    "Business to Consumer Management",
    "Ecommerce Management",
    "Export Market Development",
    "Food Regulatory Compliance",
    "General Management",
    "Manufacturing and Operations",
    "Quality Management",
    "Research and Development",
    "Workplace Safety and Health"
  ],
  "Food Services": [
    "Business Continuity Management",
    "Business Development",
    "Business Management",
    "Customer Experience",
    "Enterprise Risk Management",
    "Food and Beverage Operations",
    "Food Standards and Workplace Safety Management",
    "General Management",
    "Infocomm Technology",
    "Innovation",
    "Leadership and People Management",
    "Personal Management and Development",
    "Planning and Implementation",
    "Project Management",
    "Quality Management",
    "Risk Management, Governance and Regulatory Compliance"
  ],
  "Healthcare": [
    "Ambulance Operations Readiness",
    "Care Services",
    "Department Management",
    "Drug Compounding and Management",
    "Education for Healthcare Professions",
    "Enterprise Risk Management",
    "Ethics and Professionalism",
    "Evidence Based Practice",
    "General Management",
    "Patient and/or Client Education and Health Promotion",
    "Patient Care",
    "People Development",
    "Prehospital Patient Management",
    "Professional Practice",
    "Quality and Patient Safety",
    "Stakeholder Engagement and Partnerships"
  ],
  "Hotel and Accommodation Services": [
    "Business Development",
    "Business Management",
    "Customer Experience",
    "Executive Leadership",
    "Front Office Operations and Services",
    "General Management",
    "Housekeeping Operations",
    "Infocomm Technology and Data",
    "Marketing Communications",
    "People Management",
    "Productivity and Innovation",
    "Revenue and Distribution",
    "Risk and Compliance Management",
    "Sales and Marketing",
    "Workplace Safety and Security Management"
  ],
  "Human Resource": [
    "Employee Attraction",
    "Employee Separation",
    "General Human Resource Management",
    "Human Resource Planning",
    "Workforce Development",
    "Workforce Engagement"
  ],
  "Infocomm Technology": [
    "Analytical Thinking",
    "Business and Project Management",
    "Business Development",
    "Business Finance",
    "Design and Architecture",
    "Development and Implementation",
    "GenAI",
    "General Management",
    "Governance and Compliance",
    "Operations and User Support",
    "People Development",
    "Project Management",
    "Risk Management, Governance and Regulatory Compliance",
    "Sales and Marketing",
    "Stakeholder and Contract Management",
    "Strategy and Architecture",
    "Strategy Planning and Implementation",
    "Technology Management"
  ],
  "Intellectual Property": [
    "Business Development",
    "General Management",
    "Intellectual Property Management",
    "People Management"
  ],
  "Landscape": [
    "Analysis",
    "Arboriculture",
    "Business Management",
    "Design",
    "Environment",
    "Floristry",
    "Horticulture",
    "Landscape Engineering",
    "Landscape Implementation",
    "Nursery Management",
    "Safety"
  ],
  "Legal Services": [
    "Business",
    "Legal Advocacy & Advisory",
    "Management"
  ],
  "Logistics": [
    "Business Management",
    "Equipment, Shipment and Cargo Handling",
    "Freight Forwarding",
    "Process Improvement",
    "Solutioning and Programme Management",
    "Stakeholder and Customer Management",
    "Technology Management",
    "Transportation Management",
    "Warehouse Management",
    "Workplace Safety and Health"
  ],
  "Marine and Offshore": [
    "Business Development",
    "Business Finance",
    "General Management",
    "Marine and Offshore System Design",
    "Marine Calculations",
    "Marine Manufacturing",
    "Product Finalisation",
    "Production Management",
    "Project Management",
    "Quality Management",
    "Repair and Maintenance",
    "Research and Development",
    "Supply Chain Management",
    "Systems Engineering",
    "Technical Drawing",
    "Workplace Safety and Health"
  ],
  "Media": [
    "Analytics and Customer Insights",
    "Artificial Intelligence",
    "Arts",
    "Care Services",
    "Conceptualisation",
    "Content Post-Production",
    "Content Production Continuity",
    "Content Strategy and Planning",
    "Costume, Hair and Make-up",
    "Game Design",
    "Game Programming and Quality Assurance",
    "Game Sound",
    "General Business Management",
    "Journalism",
    "Marketing",
    "Media",
    "Media Technology and Operations",
    "Music Composition",
    "Operational Control Implementation",
    "Product Management",
    "Product, Sales and Market Management",
    "Production Accounting",
    "Production and Direction",
    "Production Design and Art",
    "Production Technical Services",
    "Professional Practice",
    "Safety and Health",
    "Safety, Health and Welfare",
    "Sales and Distribution",
    "Script and Story Development",
    "Talent Action Performance",
    "Talent Performance",
    "VFX, Animation & Design",
    "Virtual Production (VP) / In-Camera Visual Effects (ICVFX)",
    "Visual Graphics",
    "VP/ICVFX\nVIrtual Production (VP) / In-Camera Visual Effects (ICVFX)"
  ],
  "Precision Engineering": [
    "Automation Management",
    "Big Data Analytics",
    "Business and Organisational Management",
    "Engineering and Manufacturing Fundamentals",
    "Maintenance",
    "Manufacturing and Operations",
    "Network Technology Management",
    "Organisational Development",
    "Precision Manufacturing Process",
    "Procurement",
    "Product Development",
    "Production Management",
    "Productivity and Innovation",
    "Quality Management",
    "Systems Integration",
    "Technology Road Mapping",
    "Value Engineering",
    "Workplace Safety and Health Management"
  ],
  "Public Transport": [
    "Automotive Engineering",
    "Automotive Maintenance",
    "Bus Operations",
    "Business Management",
    "Corporate Governance and Policies",
    "Incident Management",
    "Maintenance Management",
    "People Management",
    "Process Improvement",
    "Rail Operations",
    "Rail Systems Maintenance",
    "Stakeholders and Customer Management",
    "Supply Chain Management",
    "Technology Management",
    "Workplace Safety and Health"
  ],
  "Retail": [
    "Analytical, Conceptual and Evaluative",
    "Brand and Channel Management",
    "Business Continuity Management",
    "Change Management",
    "Communication",
    "Copywriting",
    "Corporate Governance and Policies",
    "Customer Acquisition and Retention",
    "Customer Experience",
    "Customer Immersive Experience",
    "Design and Illustration",
    "Digital Interface Optimisation",
    "Finance",
    "Infocomm Technology (ICT)",
    "Information and Results",
    "Innovation",
    "Inventory Management",
    "Leadership and People Management",
    "Market Intelligence",
    "Outreach and Traffic Optimisation",
    "People and Relationship Management",
    "Personal Management and Development",
    "Planning and Implementation",
    "Product Management",
    "Programme and Campaign Management",
    "Project Management",
    "Public Relations",
    "Results Achievement",
    "Retail Analytics",
    "Retail Sourcing",
    "Retail System Automation and Optimisation",
    "Risk Management",
    "Sales and Marketing",
    "Supplier Relationship Management",
    "Supply Chain and Logistics Management",
    "Visual Display and Space Optimisation",
    "Workplace Housekeeping, Safety and Security"
  ],
  "Sea Transport": [
    "Business Development",
    "Business Finance",
    "Cargo Operations",
    "Customer Experience and Stakeholder Management",
    "Data Analytics and Information Technology Management",
    "Fleet Management",
    "Human Resource",
    "Investment and Financial Management",
    "Marine Engineering",
    "Marine Surveying",
    "Pilotage",
    "Port Equipment",
    "Port Operations",
    "Process Improvement",
    "Risk Management, Governance and Regulatory Compliance",
    "Ship Broking and Chartering",
    "Ship Emergency, Occupational Safety and Survival",
    "Ship Handling and Seamanship",
    "Ship Navigation",
    "Ship Operations",
    "Shipboard Safety Management Systems",
    "Strategic Planning",
    "Sustainable Maritime",
    "Systems Engineering",
    "Workplace Safety and Health"
  ],
  "Security": [
    "Business Management",
    "Incident Management",
    "Information Management",
    "Observation",
    "People Development",
    "Security Operations",
    "Security Risk Management",
    "Security Technology Management"
  ],
  "Social Service": [
    "Advocacy",
    "Care Services",
    "Casework",
    "Counselling Practice",
    "General Management",
    "Group Work",
    "Learning Programme Development and Delivery",
    "Professional Practice",
    "Programme Development and Implementation",
    "Psychological Practice",
    "Research Practice",
    "Social Policy",
    "Volunteer Partnership",
    "Youth Engagement and Development"
  ],
  "Tourism": [
    "Attractions Operations",
    "Business Development, Sales and Marketing",
    "Business Management",
    "Enterprise Risk Management",
    "Human Resource Management",
    "Infocomm Technology Management",
    "Meetings, Incentives, Conferences and Exhibitions (MICE) Operations",
    "Product Development, Content and Experience Management",
    "Project Management",
    "Tour and Travel Services Operations"
  ],
  "Trade Associations and Chambers": [
    "Analytical, Conceptual and Evaluative",
    "Business Development",
    "Business Management",
    "Customer Acquisition and Retention",
    "Executive Leadership",
    "Export Market Development",
    "General Business Management",
    "General Management",
    "Governance and Compliance",
    "Industry Development",
    "Infocomm Technology",
    "Infocomm Technology and Data",
    "Learning Delivery",
    "Learning Design",
    "Learning Programme Development and Delivery",
    "Marketing",
    "Marketing Communications",
    "People and Relationship Management",
    "People Management",
    "Project Management",
    "Research and Data Analytics",
    "Research Practice",
    "Risk and Compliance Management",
    "Risk Management and Regulatory Compliance",
    "Stakeholder and Contract Management",
    "Workforce Development"
  ],
  "Training and Adult Education": [
    "Business Development",
    "Business Finance",
    "Business Management",
    "General Management",
    "Human Capital Management",
    "Learning Analytics and Data Management",
    "Learning Assessment and Evaluation",
    "Learning Delivery",
    "Learning Design",
    "Learning Management",
    "Marketing",
    "Project Management",
    "Research and Innovation",
    "Stakeholder and Customer Management",
    "Strategic Planning",
    "Strategic Planning and Implementation",
    "Technology Development and Management",
    "Workplace Learning"
  ],
  "Water Management": [
    "Maintenance",
    "Operations Productions Planning",
    "Planning and Implementation",
    "Systems Engineering"
  ],
  "Wholesale Trade": [
    "Branding, Publicity, Digital Marketing and E-Commerce",
    "Business Development",
    "Business Finance",
    "Business Management",
    "General Management",
    "Health, Safety and Environment (HSE) Management",
    "People Development",
    "Project Management",
    "Quality Assurance and Quality Control (QA & QC) Management",
    "Research and Data Analytics",
    "Risk Management and Regulatory Compliance",
    "Stakeholder and Customer Management",
    "Strategy Planning and Implementation",
    "Trade-Related Finance Management",
    "Trading, Sales and Operations Management",
    "Workplace Safety and Health (WSH) Management"
  ],
  "Workplace Safety and Health": [
    "Audit Management",
    "Big Data Analytics",
    "Business Development",
    "General Management",
    "Generic Manufacturing Services WSQ",
    "Generic Manufacturing Skills",
    "Hazards Management",
    "Network Technology Management",
    "Operational Control Implementation",
    "Process Industry WSQ",
    "Project Management",
    "Quality Management",
    "Technology Management",
    "Workplace Safety and Health Management"
  ]
};
window.SECTOR_AREAS = SECTOR_AREAS;
